name: maintenance
description: Maintenance To-do list app

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^2.18.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.2

  # Utils
  intl: ^0.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  # data_connection_checker: ^0.3.4

  # Firebase
  firebase_core: ^2.13.1
  firebase_auth: ^4.2.6
  firebase_auth_platform_interface: ^6.11.8
  firebase_core_platform_interface: ^4.5.3
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.8.0

  # UI
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.3

  # Image Picker
  image_picker: ^0.8.7

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.1

  flutter_localizations:
    sdk: flutter
  
  
  # Notifications
  fluttertoast: ^8.2.1
  flutter_local_notifications: ^14.0.0+1
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.1.1

  # Ads
  google_mobile_ads: ^3.0.0
  flutter_markdown: ^0.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/icon/
   - assets/bottom_bar/no_color/
   - assets/bottom_bar/color/
   - assets/docs/

flutter_intl:
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21