// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgSFG7KibQmcT-Nm5t5xwF3DMRoPShFw',
    appId: '1:582937559215:android:52f8c1f1655c91cd73545a',
    messagingSenderId: '582937559215',
    projectId: 'maintenance-80a52',
    storageBucket: 'maintenance-80a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoA5HWfnTlL5KDAiOsJOMIv_c9d5ZD_E4',
    appId: '1:582937559215:ios:dcbd574c9ada0ce873545a',
    messagingSenderId: '582937559215',
    projectId: 'maintenance-80a52',
    storageBucket: 'maintenance-80a52.appspot.com',
    androidClientId: '582937559215-kgqsj69d09as0ujb7uvigstumek6lcud.apps.googleusercontent.com',
    iosClientId: '582937559215-4fjgnr10gvgblqoj0397c4t54epj5aqo.apps.googleusercontent.com',
    iosBundleId: 'com.phamvmnhut.maintenance',
  );
}
